export const countries = [
  { id: "AL", name: "Albania" },
  { id: "AT", name: "Austria" },
  { id: "BA", name: "Bosnia and Herzegovina" },
  { id: "BE", name: "Belgium" },
  { id: "BG", name: "Bulgaria" },
  { id: "BY", name: "Belarus" },
  { id: "HR", name: "Croatia" },
  // { id: "CY", name: "Republic of Cyprus" },
  { id: "CZ", name: "Czech Republic" },
  { id: "DK", name: "Denmark" },
  // { id: "EE", name: "Estonia" },
  { id: "FI", name: "Finland" },
  { id: "FR", name: "France" },
  { id: "DE", name: "Germany" },
  // { id: "GR", name: "Greece" },
  { id: "HU", name: "Hungary" },
  // { id: "IS", name: "Iceland" },
  { id: "IE", name: "Ireland" },
  { id: "IT", name: "Italy" },
  { id: "LV", name: "Latvia" },
  // { id: "LI", name: "Liechtenstein" },
  { id: "LT", name: "Lithuania" },
  { id: "LU", name: "Luxembourg" },
  // { id: "MD", name: "Moldova" },
  // { id: "MC", name: "Monaco" },
  { id: "ME", name: "Montenegro" },
  // { id: "MT", name: "Malta" },
  { id: "NL", name: "Netherlands" },
  { id: "MK", name: "North Macedonia" },
  { id: "NO", name: "Norway" },
  { id: "PL", name: "Poland" },
  { id: "PT", name: "Portugal" },
  { id: "RO", name: "Romania" },
  { id: "RU", name: "Russian Federation" },
  { id: "RS", name: "Serbia" },
  { id: "SK", name: "Slovakia" },
  { id: "SI", name: "Slovenia" },
  { id: "ES", name: "Spain" },
  { id: "SE", name: "Sweden" },
  { id: "UA", name: "Ukraine" },
  { id: "UK", name: "United Kingdom" },
];

export const citiesDitionary = [
  { id: "Wien", nameEN: "Vienna", country: "Austria" },
  { id: "Brussels", nameEN: "Brussels", country: "Belgium" },
  { id: "Praha", nameEN: "Prague", country: "Czech Republic" },
  { id: "Berlin, Stadt", nameEN: "Berlin", country: "Germany" },
  { id: "Ψευδοδημοτική Κοινότητα Αθηναίων", nameEN: "Athens", country: "Greece" },
  { id: "Barcelona", nameEN: "Barcelona", country: "Spain" },
  { id: "Sevilla", nameEN: "Seville", country: "Spain" },
  { id: "Lyon", nameEN: "Lyon", country: "France" },
  { id: "Paris", nameEN: "Paris", country: "France" },
  { id: "Torino", nameEN: "Turin", country: "Italy" },
  { id: "Milano", nameEN: "Milan", country: "Italy" },
  { id: "Roma", nameEN: "Rome", country: "Italy" },
  { id: "Palermo", nameEN: "Palermo", country: "Italy" },
  { id: "Kraków", nameEN: "Kraków", country: "Poland" },
  { id: "Wrocław", nameEN: "Wrocław", country: "Poland" },
  { id: "Gdańsk", nameEN: "Gdańsk", country: "Poland" },
  { id: "Warszawa", nameEN: "Warsaw", country: "Poland" },
  { id: "Municipiul Bucureşti", nameEN: "Bucharest", country: "Romania" },
  { id: "København", nameEN: "Copenhagen", country: "Denmark" },
  { id: "Grad Zagreb", nameEN: "Zagreb", country: "Croatia" },
  { id: "Budapest", nameEN: "Budapest", country: "Hungary" },
  { id: "Kyiv", nameEN: "Kyiv", country: "Ukraine" },
  { id: "Katowice", nameEN: "Katowice", country: "Poland" },
  { id: "Genova", nameEN: "Genoa", country: "Italy" },
  { id: "Łódź", nameEN: "Łódź", country: "Poland" },
  { id: "Stockholm", nameEN: "Stockholm", country: "Sweden" },
  { id: "Chisinau", nameEN: "Chișinău", country: "Moldova" },
  { id: "Debrecen", nameEN: "Debrecen", country: "Hungary" },
];